name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t botson-task-image .

    - name: Run Docker container
      run: docker run --name botson-task-container -d botson-task-image

    - name: Check container logs
      run: docker logs botson-task-container
