name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Docker services
      run: |
        docker-compose up -d

    - name: Load test data
      run: |
        docker-compose exec -T app python load_test_data.py

    - name: Run tests
      run: |
        docker-compose exec -T app pytest test_anomaly_count.py